# GeoSpatialAI Conda Environment Setup
# =====================================
# Complete environment for all GeoSpatialAI components:
# - Jupyter notebooks (projects 0-9)
# - ML model integration 
# - Phase 4A AI agents
# - Conservation applications
# Based on packages currently used in base environment

name: geo_env

channels:
  - conda-forge
  - defaults
  - pyviz
  - pytorch  # Added for PyTorch packages

dependencies:
  # Python version (matching current setup)
  - python=3.11
  
  # Core scientific computing (exact versions from current setup)
  - numpy=1.26.4
  - pandas=2.2.2
  - scipy>=1.10.0
  - matplotlib=3.8.4
  - seaborn>=0.12.0
  
  # Geospatial libraries (matching current versions)
  - geopandas=1.1.1
  - rasterio=1.4.3
  - cartopy>=0.21.0
  - pyproj=3.7.2
  - shapely=2.1.1
  - fiona=1.10.1
  - folium>=0.14.0
  - contextily>=1.3.0
  - libspatialindex=1.9.3
  
  # Interactive plotting and visualization (current versions)
  - plotly=5.22.0
  - bokeh>=3.1.0
  - holoviews>=1.16.0
  - geoviews>=1.9.0
  - panel>=1.0.0
  - datashader>=0.15.0
  
  # Jupyter ecosystem (matching current setup)
  - jupyter=1.0.0
  - jupyterlab=4.0.11
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=1.0.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab-variableinspector=3.1.0
  - notebook=7.0.8
  - notebook-shim=0.2.3
  - ipywidgets>=8.0.0
  - ipyleaflet>=0.17.0
  
  # Machine Learning (current versions)
  - scikit-learn=1.4.2
  - scikit-image=0.23.2
  - xgboost>=1.7.0
  - lightgbm>=3.3.0
  - statsmodels>=0.14.0
  
  # Deep Learning (compatible versions from conda)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  # tensorflow will be installed via pip to match current version
  
  # Web frameworks (for AI agents)
  - fastapi>=0.100.0
  - uvicorn>=0.20.0
  - aiohttp=3.9.5
  - httpx>=0.24.0
  
  # Data processing and APIs (current versions)
  - requests=2.32.2
  - beautifulsoup4>=4.12.0
  - lxml>=4.9.0
  - openpyxl>=3.1.0
  - xlsxwriter>=3.1.0
  - pyyaml=6.0.1
  
  # Testing framework (current version)
  - pytest=7.4.4
  - pytest-asyncio>=0.21.0
  - pytest-mock>=3.10.0
  
  # Development tools
  - black>=23.0.0
  - flake8>=6.0.0
  - pre-commit>=3.3.0
  - git>=2.40.0
  - rich>=13.0.0
  
  # Additional scientific libraries
  - netcdf4>=1.6.0
  - h5py>=3.9.0
  - zarr>=2.14.0
  - dask>=2023.5.0
  - altair>=5.0.0
  
  # Pip dependencies (not available in conda or matching current pip versions)
  - pip
  - pip:
    # Deep Learning (matching current versions)
    - tensorflow==2.16.2
    - tensorflow-hub==0.16.1
    
    # AI/LLM integration
    - openai>=1.0.0
    - anthropic>=0.5.0
    - langchain>=0.1.0
    - langchain-community>=0.0.20
    
    # Web/API tools (matching current versions)
    - pydantic==2.11.7
    - pydantic-core==2.33.2
    - starlette>=0.27.0
    
    # Conservation-specific packages
    - geojson>=3.0.0
    - pyemodnet>=0.1.0
    # - earthengine-api>=0.1.0  # Uncomment if needed
    
    # Additional ML packages
    - optuna>=3.2.0
    - mlflow>=2.5.0
    - bionumpy>=1.0.0  # For biodiversity data
    - hmmlearn>=0.3.0  # For sequence modeling
    
    # Model Context Protocol (when available)
    # - mcp>=0.8.0  # Uncomment when stable version available
    
    # Additional current packages from our environment
    - streamlit>=1.32.0  # For interactive dashboards
    - rich==13.9.4       # For beautiful terminal output
    - pytest-cov>=6.2.0  # For test coverage
    - jupyterlab-quarto>=0.3.5  # For document publishing
    
    # Logging and monitoring
    - structlog>=23.0.0
    
    # Additional data tools
    - python-dateutil>=2.8.0
    - python-dotenv>=1.0.0
    - toml>=0.10.0
    - tomlkit>=0.11.0
    - ruamel.yaml>=0.17.21
