apiVersion: v1
kind: Service
metadata:
  name: monitoring
  namespace: conservation-prod
  labels:
    app: monitoring
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: monitoring